### ISSUE TITLE
Template is currently broken

### ISSUE THREAD

**Issue by rpus** [gitpod-io/template-dotnet-core-cli-csharp#4]
This template simply does not work at present.

Opening this repo in Gitpod (in a browser, by prepending the URL as per usual instructions) gives the error:

```
/home/gitpod/dotnet/sdk/5.0.205/Roslyn/Microsoft.CSharp.Core.targets(71,5): error MSB6004: The specified task executable location "/run/containerd/io.containerd.runtime.v2.task/k8s.io/3c6886d4c832d3ace340c8396da8b50b05a483110ff649b6c91f08881b8a626a/rootfs/home/gitpod/dotnet/dotnet" is invalid. [/workspace/template-dotnet-core-cli-csharp/dotnetcore.csproj]
```

Manually running `dotnet build` (say) in the VS Code terminal gives the same error there.

**Comment by rpus** [comment]
This issue is not unique to this repo either; my own `dotnet` project also fails in Gitpod with the same error. So perhaps `dotnet` development/building is completely broken in Gitpod at present!

**Comment by dlidstrom** [comment]
The exception lektions

**Comment by chuck-confluent** [comment]
Still broken (Oct 25, 2021)

**Comment by dlidstrom** [comment]
🎉
