### ISSUE TITLE
MSB6004: The specified task executable location is invalid

### ISSUE THREAD

**Issue by ethancharles13** [gitpod-io/template-dotnet-core-cli-csharp#8]
### Bug description

This previously fixed bug has resurfaced. Trying to build or run this template causes this error message

"The specified task executable location "/run/containerd/io.containerd.runtime.v2.task/k8s.io/f99edb217eed5d3bf4c6a1e6d8158800d06d061ee1c791e0d2b0827a4296e75d/rootfs/home/gitpod/dotnet/dotnet" is invalid. [/workspace/template-dotnet-core-cli-csharp/dotnetcore.csproj]"

Thanks for creating this template and the work you have done in maintaining it. It has been very useful for me when I practice coding on my work computer, and I imagine it is helping many others as well.

### Steps to reproduce

Open template and issue build command.

**Comment by kboduch** [comment]
Temporary fix:

```
sudo su
mkdir -p /run/containerd/io.containerd.runtime.v2.task/k8s.io/bfb798ce4f4af9e90c26f8d8af7b0d04f732184b7c7e69f6f6468e63874afa53/rootfs/home/gitpod/dotnet
ln -s /home/gitpod/dotnet/dotnet /run/containerd/io.containerd.runtime.v2.task/k8s.io/bfb798ce4f4af9e90c26f8d8af7b0d04f732184b7c7e69f6f6468e63874afa53/rootfs/home/gitpod/dotnet/dotnet
```

**Comment by utam0k** [comment]
@ethanbell13 @kboduch 
Hi, thanks for raising the issue. Could you try this branch?
https://github.com/gitpod-io/template-dotnet-core-cli-csharp/tree/to/shiftfs

Please comment on this issue if you have any other questions as I would like to compile the information.
https://github.com/gitpod-io/gitpod/issues/8901

**Comment by ethancharles13** [comment]
It works great.  Thanks :)
